ranks:
  - id: newbie
    display: "&7[&f새싹&7]"
    required_minutes: 0
    luckperms_group: "rank_newbie"
    suffix: "&7[새싹]"
    view_limits:
      legendary_per_day: 1
      megaboss_per_day: 1
  - id: regular
    display: "&a[&2레귤러&a]"
    required_minutes: 180
    luckperms_group: "rank_regular"
    suffix: "&a[레귤러]"
    view_limits:
      legendary_per_day: 3
      megaboss_per_day: 3
  - id: veteran
    display: "&b[&3베테랑&b]"
    required_minutes: 600
    luckperms_group: "rank_veteran"
    suffix: "&b[베테랑]"
    view_limits:
      legendary_per_day: 6
      megaboss_per_day: 6
  - id: master
    display: "&6[&e마스터&6]"
    required_minutes: 1800
    luckperms_group: "rank_master"
    suffix: "&6[마스터]"
    view_limits:
      legendary_per_day: 12
      megaboss_per_day: 12

intercept_commands:
  legendary_aliases: ["/전설시간"]
  megaboss_aliases: ["/메가보스", "/메가보스시간"]
  dispatch_on_legendary: "checkspawns legendary"
  dispatch_on_megaboss: "checkspawns megaboss"

gui:
  title: "&8칭호 선택"
  size: 54

custom_title_item:
  name: "&d칭호 커스텀권"
  lore_lines:
    - "&7우클릭 후 채팅에 원하는 칭호를 입력하세요."
    - "&7색코드 & 및 &x&?&?&?&?&?&? 16진 RGB 지원"

storage:
  type: "yaml"
  timezone: "Asia/Seoul"

colorchat:
  gui:
    title: "&8색깔채팅"
    size: 54
    reset_button:
      material: BARRIER
      name: "&7[원래대로] 색깔 해제"
  token:
    name: "&d색깔채팅권: {color_name}"
    lore:
      - "&7우클릭하면 해당 색을 영구 보유합니다."
      - "&7/색깔채팅 GUI에서 선택해 적용하세요."
  colors:
    - { id: red,    name: "빨강",  code: "&c", material: RED_DYE }
    - { id: blue,   name: "파랑",  code: "&9", material: BLUE_DYE }
    - { id: green,  name: "초록",  code: "&a", material: LIME_DYE }
    - { id: gold,   name: "금색",  code: "&6", material: ORANGE_DYE }
    - { id: aqua,   name: "하늘",  code: "&b", material: LIGHT_BLUE_DYE }
    - { id: purple, name: "보라",  code: "&5", material: PURPLE_DYE }
    - { id: white,  name: "하양",  code: "&f", material: WHITE_DYE }
