# UltimatePlaytimeTitles 기본 설정
playtime:
  track_interval_seconds: 60

# 등급 정의 (순서대로 체크). required_minutes 기준으로 승급. group 은 LuckPerms 그룹명.
ranks:
  - id: newbie
    display: "&7뉴비"
    required_minutes: 0
    group: "newbie"
    suffix: "&7[★]"
    legendary_daily: 1
    megaboss_daily: 1
  - id: bronze
    display: "&6브론즈"
    required_minutes: 120
    group: "bronze"
    suffix: "&6[★★]"
    legendary_daily: 2
    megaboss_daily: 2
  - id: silver
    display: "&f실버"
    required_minutes: 600
    group: "silver"
    suffix: "&f[★★★]"
    legendary_daily: 3
    megaboss_daily: 3
  - id: gold
    display: "&e골드"
    required_minutes: 1500
    group: "gold"
    suffix: "&e[★★★★]"
    legendary_daily: 5
    megaboss_daily: 5

# 칭호 커스텀권 (오피 명령 /칭호 아이템 으로 현재 든 아이템을 템플릿으로 저장 가능)
custom_ticket:
  name: "&d칭호 커스텀권"
  lore:
    - "&7우클릭하여 원하는 칭호를 등록합니다."
    - "&7색코드는 & 를 사용하세요 (허용된 색만 가능)."

# GUI 제목
gui:
  titles_title: "&a칭호 GUI"
  colorchat_title: "&b색깔채팅 GUI"

# 색깔채팅: 한글명 -> 코드 문자
colors:
  빨강: "c"
  노랑: "e"
  주황: "6"
  초록: "a"
  파랑: "9"
  하늘: "b"
  보라: "5"
  분홍: "d"
  흰색: "f"
  검정: "0"
  회색: "7"
  연회색: "8"
  청록: "3"
  에메랄드: "a"
  금색: "6"
  남색: "1"
  진초록: "2"
  진하늘: "3"
  진보라: "5"
  진빨강: "4"
