check-interval-seconds: 60

# PlaceholderAPI key that resolves to total playtime in seconds.
# Default matches Zach_FR Playtime: %playtime_seconds_all%
playtime-seconds-placeholder: "%playtime_seconds_all%"

messages:
  prefix: "&7[&a승급&7]&r "
  status: "&e다음 등급: &b%next_group% &7| &e남은 플레이타임: &b%remaining%"
  maxed: "&a이미 최고 등급까지 승급 완료 상태입니다."
  promoted: "&a축하합니다! &e%new_group% &a등급으로 승급되었습니다."
  missing_papi: "&cPlaceholderAPI 또는 Playtime 플러그인이 없어 승급 기능을 사용할 수 없습니다."
  missing_lp: "&cLuckPerms가 설치되어 있지 않아 플러그인을 비활성화합니다."

# Rank rules (seconds required are absolute total playtime).
ranks:
  - name: "Member"
    promote-to: "member"
    required-seconds: 3600
    remove-groups: ["default"]
  - name: "VIP"
    promote-to: "vip"
    required-seconds: 7200
    remove-groups: ["member"]
  - name: "MVP"
    promote-to: "mvp"
    required-seconds: 21600
    remove-groups: ["vip"]