title_suffix:
  enabled: true
  priority: 100
  format: "&7[&f{title}&7]"
  clear_command: "lp user {player} meta removesuffix {priority}"
  set_command: "lp user {player} meta setsuffix {priority} {suffix}"

auto_promote:
  enabled: true
  add_command: "lp user {player} parent add {group}"
  remove:
    enabled: false
    remove_previous_rank_group: true
    groups_extra: []
    remove_command: "lp user {player} parent remove {group}"

ranks:
  - id: newbie
    display: "&7[&f새싹&7]"
    required_minutes: 0
    luckperms_group: "rank_newbie"
    view_limits:
      legendary_per_day: 1
      megaboss_per_day: 1
  - id: regular
    display: "&a[&2레귤러&a]"
    required_minutes: 180
    luckperms_group: "rank_regular"
    view_limits:
      legendary_per_day: 3
      megaboss_per_day: 3
  - id: veteran
    display: "&b[&3베테랑&b]"
    required_minutes: 600
    luckperms_group: "rank_veteran"
    view_limits:
      legendary_per_day: 6
      megaboss_per_day: 6
  - id: master
    display: "&6[&e마스터&6]"
    required_minutes: 1800
    luckperms_group: "rank_master"
    view_limits:
      legendary_per_day: 12
      megaboss_per_day: 12

intercept_commands:
  legendary_aliases: ["/전설시간"]
  megaboss_aliases: ["/메가보스", "/메가보스시간"]
  dispatch_on_legendary: "checkspawns legendary"
  dispatch_on_megaboss: "checkspawns megaboss"

gui:
  title: "&8칭호 선택"
  size: 54

custom_title_item:
  name: "&d칭호 커스텀권"
  lore_lines:
    - "&7우클릭 후 채팅에 원하는 칭호를 입력하세요."
    - "&7색코드 & 및 &x&?&?&?&?&?&? 16진 RGB 지원"

storage:
  type: "yaml"
  timezone: "Asia/Seoul"

colorchat:
  gui:
    title: "&8색깔채팅"
    size: 9
    reset_button:
      material: BARRIER
      name: "&7[원래대로] 색깔 해제"
  token:
    name: "&d색깔채팅권: {color_name}"
    lore:
      - "&7우클릭하면 해당 색을 영구 보유하고 즉시 적용합니다."
      - "&7/색깔채팅 GUI에서 변경/해제 가능"
  colors:
    - { id: black,        name: "검정",    code: "&0", material: BLACK_DYE }
    - { id: dark_blue,    name: "진파랑",  code: "&1", material: BLUE_DYE }
    - { id: dark_green,   name: "진초록",  code: "&2", material: GREEN_DYE }
    - { id: dark_aqua,    name: "청록",    code: "&3", material: CYAN_DYE }
    - { id: dark_red,     name: "진빨강",  code: "&4", material: RED_DYE }
    - { id: dark_purple,  name: "진보라",  code: "&5", material: PURPLE_DYE }
    - { id: gold,         name: "금색",    code: "&6", material: ORANGE_DYE }
    - { id: gray,         name: "회색",    code: "&7", material: LIGHT_GRAY_DYE }
    - { id: dark_gray,    name: "진회색",  code: "&8", material: GRAY_DYE }
    - { id: blue,         name: "파랑",    code: "&9", material: LAPIS_BLOCK }
    - { id: green,        name: "초록",    code: "&a", material: LIME_DYE }
    - { id: aqua,         name: "하늘",    code: "&b", material: LIGHT_BLUE_DYE }
    - { id: red,          name: "빨강",    code: "&c", material: RED_WOOL }
    - { id: light_purple, name: "분홍",    code: "&d", material: MAGENTA_DYE }
    - { id: yellow,       name: "노랑",    code: "&e", material: YELLOW_DYE }
    - { id: white,        name: "하양",    code: "&f", material: WHITE_DYE }