# UltimateTitleRank v6 - 기본 설정
general:
  spawn_run_as: player  # player | console
  spawn_temp_permission: ''  # e.g. pixelmon.command.checkspawns
  spawn_temp_permission_ticks: 2
  chat_mode: augment
  force_replace_when_missing: false  # augment | replace | off
  timezone: Asia/Seoul
  daily_reset_hour: 4    # 매일 04:00(KST)에 횟수 초기화
  chat_format_enabled: true   # true면 채팅 끝에 접미사/접두사로 칭호를 붙입니다.
  title_position: suffix       # prefix | suffix


# 등급(럭펌 그룹)별 승급 기준과 /checkspawns 제한
ranks:
  - id: "bronze"
    display: "&7브론즈"
    required_minutes: 60
    luckperms_group: "bronze"
    daily_limits:
      legendary_checks: 1
      megaboss_checks: 0
  - id: "silver"
    display: "&f실버"
    required_minutes: 180
    luckperms_group: "silver"
    daily_limits:
      legendary_checks: 2
      megaboss_checks: 1
  - id: "gold"
    display: "&6골드"
    required_minutes: 360
    luckperms_group: "gold"
    daily_limits:
      legendary_checks: 3
      megaboss_checks: 2
  - id: "diamond"
    display: "&b다이아"
    required_minutes: 720
    luckperms_group: "diamond"
    daily_limits:
      legendary_checks: 5
      megaboss_checks: 3

colorchat:
  gui_title: "&8색깔채팅 선택"
  cancel_button_name: "&7원래 색으로"
  # GUI에 표시될 색 목록 (이름=표시이름, code=색코드)
  colors:
    RED: { name: "&c빨강", code: "&c" }
    GOLD: { name: "&6주황", code: "&6" }
    YELLOW: { name: "&e노랑", code: "&e" }
    GREEN: { name: "&a연두", code: "&a" }
    DARK_GREEN: { name: "&2초록", code: "&2" }
    BLUE: { name: "&9파랑", code: "&9" }
    AQUA: { name: "&b하늘", code: "&b" }
    DARK_AQUA: { name: "&3청록", code: "&3" }
    LIGHT_PURPLE: { name: "&d분홍", code: "&d" }
    DARK_PURPLE: { name: "&5보라", code: "&5" }
    WHITE: { name: "&f하양", code: "&f" }
    GRAY: { name: "&7회색", code: "&7" }
    DARK_GRAY: { name: "&8진회색", code: "&8" }
    BLACK: { name: "&0검정", code: "&0" }

