name: UltimatePlaytimeTitles
main: com.minkang.ultimate.playtimetitles.Main
version: 1.0.1
api-version: 1.16
author: minkang
description: Playtime-based LuckPerms rank & title + color chat GUI
commands:
  승급:
    description: 플레이타임 기준 자동 승급 즉시 검사
    usage: /승급
  승급조건:
    description: 다음 등급까지 필요한 시간/등급 확인
    usage: /승급조건
    aliases: [next, nexttier]
  전설시간:
    description: /checkspawns legendary 콘솔 대행 (일일 횟수 제한)
    usage: /전설시간
  전설시간횟수:
    description: 전설시간 사용 가능/사용 현황
    usage: /전설시간횟수
  메가보스:
    description: /checkspawns megaboss 콘솔 대행 (일일 횟수 제한)
    usage: /메가보스
  메가보스횟수:
    description: 메가보스 사용 가능/사용 현황
    usage: /메가보스횟수
  칭호:
    description: 칭호 관리 (열기/생성/삭제/목록/아이템)
    usage: /칭호 <열기|생성|삭제|목록|아이템> [...]
  색깔채팅:
    description: 색깔채팅 GUI/지급/제거/목록
    usage: /색깔채팅 <열기|지급|제거|목록> [...]
