
name: UltimateTitleRank
main: com.minkang.ultimate.UltimateTitleRank
version: 1.0.0
api-version: 1.16
author: Mingang
softdepend: [LuckPerms, Playtime, PlaceholderAPI]
commands:
  title:
    description: Open title GUI / manage titles
    usage: /title [생성|목록] [칭호이름]
    aliases: [칭호]
    permission: ""
  rankinfo:
    description: Show your rankup condition
    usage: /rankinfo
    aliases: [승급,승급조건]
    permission: ""
permissions:
  ultimatetitlerank.admin:
    default: op
    description: 관리자 전용 권한
  ultimatetitlerank.use:
    default: true
    description: 일반 유저 사용 권한
