name: UltimateAutoRank
main: com.minkang.ultimate.autorank.UltimateAutoRankPlugin
version: 1.1.2
api-version: 1.16
description: "Auto promotion by playtime using Playtime(ZachFR)+PlaceholderAPI+LuckPerms"
author: "minkang"
softdepend: [LuckPerms, PlaceholderAPI, Playtime]
commands:
  rank:
    description: "승급 관련 명령"
    usage: "/rank status|조건"
    aliases: [승급]